report-bugs-by-assignee: fix multiple issues
- correct the undefined reference to bug_data
- use print() rather than os.write(), getting unicode support along
  with it
- modernize the code in a couple of places
- drop unused imports

Signed-off-by: Steve Beattie <steve.beattie@canonical.com>