check-syntax: fix traceback when release is missing
When missing a release, check-syntax was failing with the following
traceback:

Traceback (most recent call last):
  File "./scripts/check-syntax", line 325, in <module>
      print("%s: %d: %s missing supported release '%s'" % (cvepath, srcmap['pkgs'][pkg], pkg, rel), file=sys.stderr)
TypeError: %d format: a number is required, not dict

Since the missing release_package pair doesn't have a line number,
just use line 1. (Something smarter could be done here, but this was the
simplest solution.)

Signed-off-by: Steve Beattie <steve.beattie@canonical.com>